### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required

### ISSUE THREAD

**Issue by rosevinod** [nWidart/Laravel-Broadway-Demo#1]
I got following errors;

PHP Fatal error:  require(): Failed opening required

After coping the autoload.php  i got following 

 [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Illuminate\Html\HtmlServiceProvider' not found

**Comment by nWidart** [comment]
Ah yes, I need to use the new `LaravelCollective/html` package instead of the old not maintained html package.

**Comment by nWidart** [comment]
Fixed it in the latest commit.
