### ISSUE TITLE
Sample MyEventListener tries to handle non-existent interface

### ISSUE THREAD

**Issue by blrobin2** [nWidart/Laravel-Broadway-Demo#2]
Broadway's EventListenerInterface expects to handle a DomainMessage. The sample MyEventListener in the Modeles\Acme\Listeners namespace is trying to handle a DomainMessageInterface, which does not exist. Just changing MyEventListener to adhere to the EventListenerInterface contract should fix the problem. Not a huge deal, but I figured you would want to know.

**Comment by nWidart** [comment]
Thank you , probably happened during one of their updates.

I'll gladly merge a pull request, as I don't have time at the moment to look into this.

**Comment by blrobin2** [comment]
I understand completely. I've submitted a pull request.

**Comment by nWidart** [comment]
You forked the repo and committed, but not sent a  pull-request.

**Comment by blrobin2** [comment]
Oops, did it to my fork by mistake _smacks forehead_. I've sent the pull
request.
