### ISSUE TITLE
http://localhost:8000/parts/index goes to Woops  

### ISSUE THREAD

**Issue by joostshao** [nWidart/Laravel-Broadway-Demo#6]
url: http://localhost:8000/parts/index

Whoops, looks like something went wrong.

and the table event_store is empty.

i don't know why  appear Woops

**Comment by nixilla** [comment]
try `echo -e "APP_ENV=local\nAPP_DEBUG=true\n" >> .env` and refresh page

**Comment by joostshao** [comment]
thank you !
